# Generated by Django 4.2.6 on 2023-10-26 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('when_created', models.DateField(default=datetime.datetime.now)),
                ('Who_created', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(upload_to='univesity_photos/')),
                ('university_bio', models.TextField()),
                ('location', models.CharField(default='', max_length=50)),
                ('contact_with_admin', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'University',
            },
        ),
    ]
